[tool.poetry]
name = "cultural-app"
version = "0.1.0"
description = ""
authors = ["Charles De Dampierre <charles.de-dampierre@hec.edu>"]
readme = "README.md"
packages = [{include = "cultural_app"}]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.5.2"
plotly = "^5.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
